### 1. Solving for x

In [37]:
import sympy as sym
from IPython.display import display, Math

In [2]:
x = sym.symbols('x')

expr = 2*x + 4 - 9

sym.solve(expr)


[5/2]

In [5]:
display(Math('\\text{ The solution is } %s \\text{ is x =} %g' %(sym.latex(expr), sym.solve(expr)[0])))

<IPython.core.display.Math object>

In [10]:
expr = x**2-4
sol = sym.solve(expr)
for i in range(0, len(sol)):
    print('Solution #' + str(i+1) + ' is ' + str(sol[i]))

Solution #1 is -2
Solution #2 is 2


In [16]:
y = sym.symbols('y')

expr = x/4 - x*y + 5

sym.solve(expr, y)

[(x + 20)/(4*x)]

### 2. Solving for x exercises

In [5]:
#1)
q = sym.symbols('q')
eq = 3*q + 4/q + 3 - (5*q + 1/q + 1)
display(Math(sym.latex(eq.simplify())))
display(Math('q=' + sym.latex(sym.solve(eq, q))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [7]:
#2)
eq = 2*q + 3*q**2 - 5/q - 4/q**3
display(Math(sym.latex(eq.simplify())))
display(Math(sym.latex(eq.cancel())))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [11]:
# 3)
expr = (sym.sqrt(3) + sym.sqrt(15)*q)/(sym.sqrt(2) + sym.sqrt(10)*q)
display(Math(sym.latex(expr)))

<IPython.core.display.Math object>

In [15]:
expr.subs(q,1000).evalf()

1.22474487139159

In [16]:
display(Math(sym.latex(expr.simplify())))

<IPython.core.display.Math object>

### 3. Expanding terms

In [25]:
# x = sym.symbols('x')
from sympy.abc import x
term1 = (4*x +5)
term2 = x

print(term1 * term2)
display(Math(sym.latex(sym.expand(term1 * term2))))

x*(4*x + 5)


<IPython.core.display.Math object>

In [27]:
term3 = x - 7

display(Math(sym.latex(term1 * term3)))
display(Math(sym.latex(sym.expand(term1 * term3))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [29]:
from sympy.abc import y

expr = x * (2*y**2 - 5 **x /x)
display(Math(sym.latex(expr)))
display(Math(sym.latex(expr.expand())))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [30]:
%whos

Variable   Type        Data/Info
--------------------------------
Math       type        <class 'IPython.core.display.Math'>
display    function    <function display at 0x00000207AD2A9E40>
eq         Mul         (sqrt(15)*q + sqrt(3))/(sqrt(10)*q + sqrt(2))
expr       Mul         x*(-5**x/x + 2*y**2)
q          Symbol      q
sym        module      <module 'sympy' from 'F:\<...>ges\\sympy\\__init__.py'>
term       Add         4*x + 5
term1      Add         4*x + 5
term2      Symbol      x
term3      Add         x - 7
x          Symbol      x
y          Symbol      y


#### 3. Exercises

In [35]:
Fxy = (4 + x)*(2-y)

numrange = range(0,3)

for xi in numrange:
    for yi in numrange:
        print('When x=%g and y=%g, f(x,y)=%g' %(xi, yi, Fxy.subs({x:xi, y:yi})))

When x=0 and y=0, f(x,y)=8
When x=0 and y=1, f(x,y)=4
When x=0 and y=2, f(x,y)=0
When x=1 and y=0, f(x,y)=10
When x=1 and y=1, f(x,y)=5
When x=1 and y=2, f(x,y)=0
When x=2 and y=0, f(x,y)=12
When x=2 and y=1, f(x,y)=6
When x=2 and y=2, f(x,y)=0


### 4. Creating and accessing matrices with numpy

In [36]:
import numpy as np

In [40]:
A = [[1,2], [3,4]]

type(A)

list

In [45]:
A = np.array(A)
type(A)
print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [50]:
mat = np.zeros([4,6])

mat[0,1] = 2

mat[2,4] = 7

mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [52]:
numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi, coli] = (-1)**(rowi + coli)

mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

#### 4. Exercise

In [56]:
x,y = sym.symbols('x y')
Fxy = (4 + x) * (2 - y)
xyset = range(0, 3)

outmat = np.zeros([len(xyset), len(xyset)])

for i in xyset:
    for j in xyset:
        outmat[i, j] = Fxy.subs({x:i, y:j})

display(Math(sym.latex(sym.sympify(outmat))))

<IPython.core.display.Math object>

### 5. Exercise Create a multiplication table

In [61]:
nums = range(1,11)

matmult = np.zeros([len(nums), len(nums)],dtype=int)

for rowi in nums:
    for coli in nums:
        matmult[rowi - 1, coli - 1] = rowi * coli

display(Math(sym.latex(sym.sympify(matmult))))

<IPython.core.display.Math object>